[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable optimizer to reduce bytecode size (AssociationsStore must be <= 24KB)
optimizer = true
optimizer_runs = 200

# If still above the limit, we can enable this too (more aggressive size reduction):
# via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
